### PR TITLE
Jenkins LTS 1.580.3

### PR DESCRIPTION
**Pull request by drautureau**

### CODE REVIEW

**Comment by hgomez** [comment]
David, could you also update _service file ?
It's required by OBS : https://build.opensuse.org/package/show/home:henri_gomez:devops-incubator/myjenkins-lts

**Comment by drautureau** [comment]
Is https://github.com/drautureau/devops-incubator/commit/ed7203aa51fb6089bb2c1a50aeb1a807445f331c what you are expecting?
Sorry, I was not aware of it.

**Comment by hgomez** [comment]
It's for OBS rpm factory.
Thanks for PR

**Comment by hgomez** [comment]
Build in progress 

https://build.opensuse.org/package/show/home:henri_gomez:devops-incubator/myjenkins-lts

**Pull request merged**
